Projet_44location/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('login_settings.urls')),
    path('', include('cars.urls')),
    path('', include('reservations_management.urls')),
    path('', include('customer.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views

app_name = 'cars'

urlpatterns = [
    path('all_cars/', views.all_cars, name='all_cars'),
    path('car_detail/<str:pk>/', views.car_detail, name='car_detail'),
    path('add_car/', views.add_car, name='add_car'),
    path('update_car/<str:pk>/', views.update_car, name='update_car'),
    path('delete_car/<str:pk>/', views.delete_car, name='delete_car'),
    path('article/', views.article, name='article'),
    path('all_cars/recherche/<str:marque>/', views.recherche, name='recherche')
]

customer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'customer'

urlpatterns = [
    path('settings/<str:pk>/', views.user_settings, name='user_settings'),

    path('delete_account/<str:pk>/', views.delete_account_from_customer, name='delete_account_from_customer'),

    path('customer_dashboard/<str:customer_pk>/', views.customer_dashboard, name='customer_dashboard'),

    path('create_reservation_from_customer/<str:car_pk>/', views.create_reservation_from_customer, name='create_reservation_from_customer'),

    path('update_reservation_from_customer_1/<str:reservation_pk>/', views.update_reservation_from_customer_1, name='update_reservation_from_customer_1'),

    path('update_reservation_from_customer_2/<str:reservation_pk>/', views.update_reservation_from_customer_2, name='update_reservation_from_customer_2'),

    path('delete_reservation_customer/<str:reservation_pk>/', views.delete_reservation_from_customer, name='delete_reservation_from_customer'),

]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('search_car-<car>/', views.recherche, name='search_car'),
]

customer/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User, AbstractUser

''' a tester pour le fixtures always create a custom user model in the beginning of the projet
class CustomUser(AbstractUser):
    is_client = models.BooleanField(default=False, null=True, blank=True)
    is_employe = models.BooleanField(default=False, null=True, blank=True)
'''


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True, unique=True)
    profile_pic = models.ImageField(default="tn_cool.jpg", null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    @property
    def profileURL(self):
        try:
            url = self.profile_pic.url
        except:
            url = ''
        return url

    def __str__(self):
        return self.email

customer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from reservations_management.models import *
from .models import *
from django.db import models
from django.forms import ModelForm


''' A tester pour le fixture
class CustomUserCreationFom(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = '__all__'
'''


# Permet de créer un formulaire qui va reprendre le formulaire de base de Django
# pour y ajouter un champ email qui sera obligatoire afin de rajouter tous ces champs
# au model User prédéfini de Django
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


# Permet de créer un formulaire sans le customiser en reprenant directement
# le formulaire de base de Django et en y ajoutant la référance du model User de
# Django qui est aussi prédéfini
# class CreateUserForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password1', 'password2']


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']


class ReservationFormByCustomer1(ModelForm):

    class Meta:

        model = Reservation
        fields = '__all__'
        exclude = ['date_location_start', 'hours_kms_price', 'note', 'customer', 'status', 'date_location_end']


class ReservationFormByCustomer2(ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'
        exclude = ['status', 'car', 'customer', 'date_location_end', 'hours_kms_price', 'date_location_start']

customer/views.py
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import logout
from django.contrib import messages
from reservations_management.filters import ReservationFilter
from login_settings.decorators import allowed_user
from cars.models import Car, Price
from .forms import *
from .models import *
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail, BadHeaderError


# from utils import date     dont work the thing with the date mock


@login_required(login_url='login')
@allowed_user(allowed_roles=['customer', 'admin'])
def user_settings(request, pk):
    customer = Customer.objects.get(id=pk)
    form = CustomerForm(instance=customer)
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()
            messages.success(request, f'Update saved !')

    context = {'form': form, 'customer': customer}
    return render(request, 'customer/user_settings.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['customer', 'admin'])
def delete_account_from_customer(request, pk):
    customer = Customer.objects.get(id=pk)
    if request.method == 'POST':
        customer.delete()
        logout(request)
        messages.warning(request, f"Account has been deleted !")
        return redirect("home:homepage")

    context = {'customer': customer}
    return render(request, 'customer/delete_account.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['customer'])
def customer_dashboard(request, customer_pk):
    customer = Customer.objects.get(id=customer_pk)

    reservations = customer.reservation_set.all().order_by('-date_created')
    reservation_count = reservations.count()

    myFilter = ReservationFilter(request.GET, queryset=reservations)
    reservations = myFilter.qs

    context = {'customer': customer, 'reservations': reservations, 'reservation_count': reservation_count,
               'myFilter': myFilter}
    return render(request, 'customer/customer_dashboard.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['customer'])
def create_reservation_from_customer(request, car_pk):
    car = Car.objects.get(pk=car_pk)
    car_price = Price.objects.all().filter(car=car_pk)
    customer = request.user.customer
    available_date_check = datetime.now().replace(microsecond=0).replace(second=0).isoformat()

    if request.method == 'POST':
        form = request.POST
        Reservation.objects.create(
            customer=customer,
            car=car,
            status='Pending',
            hours_kms_price=form['hours_kms_price'],
            note=form['note'],
            date_location_start=form['date_location_start'],
        )

        date_location = form['date_location_start']
        note = form['note']
        hours_kms_price = form['hours_kms_price']

        contextformail = {'date_location': date_location, 'note': note, 'hours_kms_price': hours_kms_price, 'customer': customer, 'car': car}

        subject = f'New reservation demand for {customer}'
        html_message = render_to_string('customer/reservation_created_mail.html', contextformail)
        plain_message = strip_tags(html_message)
        from_email = customer.email
        to_email = settings.EMAIL_HOST_USER

        try:
            send_mail(
                subject,
                plain_message,
                from_email,  # from email
                # [form['email']], another way to pick up the mail from a form
                [to_email],  # destination email
                html_message=html_message,
                fail_silently=False
            )
        except BadHeaderError:
            return HttpResponse('Invalid header found.')

        messages.success(request, f'Your reservation for the {car} is done, you will receive a confirmation per mail in the next 24h !')
        return redirect('customer:customer_dashboard', customer_pk=customer.pk)

    else:
        context = {'car_price': car_price, 'car': car, 'customer': customer, 'available_date_check': available_date_check}
        return render(request, 'customer/reservation_from_customer.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['customer'])
def update_reservation_from_customer_1(request, reservation_pk):
    reservation = Reservation.objects.get(id=reservation_pk)
    form = ReservationFormByCustomer1(instance=reservation)
    if request.method == 'POST':
        form = ReservationFormByCustomer1(request.POST, instance=reservation)
        if form.is_valid():
            form.save()
            return redirect("customer:update_reservation_from_customer_2", reservation_pk=reservation.pk)

    else:
        context = {'form': form}
        return render(request, 'customer/update_reservation_from_customer_1.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['customer'])
def update_reservation_from_customer_2(request, reservation_pk):
    reservation = Reservation.objects.get(pk=reservation_pk)
    customer = request.user.customer
    car = reservation.car
    form = ReservationFormByCustomer2(instance=reservation)
    car_price = Price.objects.all().filter(car=car.pk) # car in red must be the name in the Price field
    available_date_check = datetime.now().replace(microsecond=0).replace(second=0).isoformat()
    if request.method == 'POST':
        form = ReservationFormByCustomer2(request.POST, instance=reservation)
        normalform = request.POST
        if form.is_valid():
            form.save()

        date_location = normalform['date_location_start']
        note = normalform['note']
        hours_kms_price = normalform['hours_kms_price']

        contextformail = {'date_location': date_location, 'note': note, 'hours_kms_price': hours_kms_price,
                          'customer': customer, 'car': car}

        subject = f'Reservation update for {customer}'
        html_message = render_to_string('customer/reservation_update_mail.html', contextformail)
        plain_message = strip_tags(html_message)
        from_email = customer.email
        to_email = settings.EMAIL_HOST_USER

        try:
            send_mail(
                subject,
                plain_message,
                from_email,  # from email
                # [form['email']], another way to pick up the mail from a form
                [to_email],  # destination email
                html_message=html_message,
                fail_silently=False
            )
        except BadHeaderError:
            return HttpResponse('Invalid header found.')

        messages.success(request,
                         f'Your update for the {car} is done, you will receive a confirmation per mail in the next 24h !')
        return redirect('customer:customer_dashboard', customer_pk=customer.pk)

    else:
        context = {'form': form, 'car_price': car_price, 'car': car, 'reservation_pk': reservation_pk, 'customer': customer, 'available_date_check': available_date_check}
        return render(request, 'customer/update_reservation_from_customer_2.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['customer'])
def delete_reservation_from_customer(request, reservation_pk):
    reservation = get_object_or_404(Reservation, pk=reservation_pk)
    customer = reservation.customer
    if request.method == 'POST':
        reservation.delete()
        return redirect("customer:customer_dashboard", customer_pk=customer.pk)

    context = {'reservation': reservation, 'customer': customer}
    return render(request, 'customer/delete_reservation_from_customer.html', context)



 # # date_location_start = form['date_location_start']
        # # if date_location_start <= date.today():
        # #     raise ValidationError(_('Date should be in the future.'))
        #     # messages.warning(request, f'Select a futur date from now please')
        #     # redirect('customer:create_reservation_from_customer')
        # elif date_location_start > date.today():

customer/templates/customer/customer_dashboard.html
{% extends 'home/header.html' %}
{% load static %}
<!-- this template belong to perparim -->
{% block content %}

<div class="row">
    <div class="col s12 m12 l12 xl12">
      <div class="card white black-text darken-4">
        <div class="card-content">
            <span class="card-title center">My reservations</span>
            <p>Total {{reservation_count}}</p>
            <table class="table responsive-table highlight">
                <thead class="blue">
                    <tr>
                        <th>Car</th>
                        <th>Price</th>
                        <th>Date Reserved</th>
                        <th>Status</th>
<!--                        <th>Note</th>-->
                        <th>Update</th>
<!--                        <th>Remove</th>-->
                    </tr>
                </thead>

                <tbody>
                    {% for reservation in reservations %}
                        <tr>
                            <td>{{reservation.car}}</td>
                            <td>{{reservation.hours_kms_price}}</td>
                            <td>{{reservation.date_location_start}}</td>
                            <td>{{reservation.status}}</td>
<!--                            <td>{{reservation.note|linebreaksbr}}</td>-->
  <td><a class="btn white black-text waves-effect waves-green" href="{% url 'customer:update_reservation_from_customer_1' reservation_pk=reservation.pk %}">Update</a></td>
<!--                            <td><a class="btn white black-text waves-effect waves-red" href="{% url 'customer:delete_reservation_from_customer' reservation_pk=reservation.pk %}">Delete</a></td>-->
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
      </div>
    </div>
</div>

{% endblock %}

customer/templates/customer/delete_account.html
{% extends 'home/header.html' %}
{% load static %}
<!-- this template belong to perparim -->
{% block content %}

<div class="row container">

    <div class="col s12 m12 l12 xl12 center ">
      <div class="card white black-text">
        <div class="card-content ">
          <span class="card-title">Account deleting</span>
            <p>Are you sure you want to delete your account ?</p>
            <form action="{% url 'customer:delete_account_from_customer' customer.id %}" method="post" onsubmit="myButton.disabled=true;return true;">
                {% csrf_token %}

                <div class="card-action">
                    <input type="submit" value="Confirm" class="btn white black-text waves-effect waves-green" name="myButton">
                    <a href="{% url 'customer:user_settings' customer.id %}" class="btn white black-text waves-effect waves-red">Cancel</a>
                </div>

            </form>
        </div>
      </div>
    </div>
</div>

{% endblock %}

customer/templates/customer/delete_reservation_from_customer.html
{% extends 'home/header.html' %}
{% load static %}
<!-- this template belong to hanefi -->
{% block content %}

<div class="row container">

    <div class="col s12 m12 l12 xl12 center ">
      <div class="card white black-text">
        <div class="card-content ">
          <span class="card-title">Reservation deleting</span>
            <p>Are you sure you want to delete your reservation for {{reservation}}?</p>
            <form action="{% url 'customer:delete_reservation_from_customer' reservation_pk=reservation.pk %}" method="post" onsubmit="myButton.disabled=true;return true;">
                {% csrf_token %}
                <div class="card-action">
                    <input type="submit" value="Confirm" class="btn white black-text waves-effect waves-green" name="myButton">
                    <a href="{% url 'customer:customer_dashboard' customer_pk=customer.id %}" class="btn white black-text waves-effect waves-red">Cancel</a>
                </div>

            </form>
        </div>
      </div>
    </div>
</div>

{% endblock %}

customer/templates/customer/reservation_created_mail.html
<!-- this template belong to hanefi -->

<h2>A new reservation demand has been created from {{customer}}</h2>

<h3>Reservation details:</h3>
<p>
    <table>

        <thead>
            <tr>
                <th>Customer name</th>
                <th>Choosen car</th>
                <th>Date and time of the location</th>
                <th>Hours, kms and price</th>
                <th>Comment</th>
                <th>Status</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td>{{customer.name}}</td>
                <td>{{car}}</td>
                <td>{{date_location}}</td>
                <td>{{hours_kms_price}}</td>
                <td>{{note}}</td>
                <td>Pending</td>
            </tr>
        </tbody>
    </table>
</p>

customer/templates/customer/reservation_from_customer.html
{% extends 'home/header.html' %}
{% load static %}
<!-- this template belong to hanefi -->
{% block content %}

<div class="row container">
    <div class="col s12 m12 l12 xl12">
      <div class="card white">

        <div class="card-image">
            <div class="carousel carousel-slider">
                <a class="carousel-item"><img src="{{car.image1}}" class="responsive-img"></a>
                <a class="carousel-item"><img src="{{car.image2}}" class="responsive-img"></a>

                <a class="carousel-item"><img src="{{car.image3}}" class="responsive-img"></a>
                <a class="carousel-item" ><img src="{{car.image4}}" class="responsive-img"></a>
            </div>
            <span class="card-title">{{car.model}}</span>
        </div>

        <div class="card-content black-text">
            <!-- Form with no modelForm -->
            <form action="" method="post" onsubmit="myButton.disabled=true;return true;">
                {% csrf_token %}

                <div class="progress">
                    <div class="determinate blue" id="full_determinate_bar"></div>
                </div>

                <h3 class="center">Reservation for {{car}}</h3>

                <div class="input-field col s12 m12 l12 xl6">
                    <select required name="hours_kms_price">
                        <option value="" disabled selected>Choose your option</option>
                        {% for price in car_price %}
                        <option value="{{price.price_category.hours}} hours | {{price.price_category.kms}} = {{price.car_price}} CHF">{{price}}</option>
                        {% endfor %}
                        <option value="For a week">A week (an admin will contact you after your confirmation)</option>
                    </select>
                    <label>Options selections</label>
                </div>

                <div class="col s12 m12 l12 xl6">
                    <span>Date and time of the location</span>
                    <div class="input-field inline">
                        <input required type="datetime-local" id="date_location_start" name="date_location_start" min="{{available_date_check}}">
                    </div>
                </div>


                <div class="row">
                    <div class="input-field col s12 m12 l12 xl10">
                        <i class="material-icons prefix">mode_edit</i>
                        <textarea id="textarea1" class="materialize-textarea" name="note" data-length="100"></textarea>
                        <label for="textarea1">Write a comment...</label>
                    </div>
                </div>

                <input type="submit" name="myButton" value="Confirm" class="btn white black-text waves-effect waves-green">

            </form>
        </div>

        <div class="card-action">
        <a href="{% url 'cars:all_cars' %}" class="btn white black-text waves-effect waves-green">Return to cars choice</a>

        <a href="{% url 'home:homepage' %}" class="btn white black-text waves-effect waves-green">Return to homepage</a>
        </div>

      </div>
    </div>
</div>

{% endblock content %}


<!--            <div class="row">-->
<!--                <div class="input-field col s12 m12 l12 xl12">-->
<!--                 <select required name="hours_kms_price">-->
<!--                    <option value="" disabled selected>Choose your option</option>-->
<!--                    {% for price in car_price %}-->
<!--                    <option value="{{price.price_category.hours}} | {{price.price_category.kms}} = {{price.car_price}} CHF">{{price}}</option>-->
<!--                    {% endfor %}-->
<!--                    <option disabled="disabled" value="For a week contact us please">For a week contact us please</option>-->

<!--                </select>-->
<!--                <label>Options selections</label>-->
<!--                </div>-->
<!--            </div>-->

customer/templates/customer/reservation_update_mail.html
<!-- this template belong to hanefi -->

<h2>An update has been made from {{customer}}</h2>

<h3>Reservation details:</h3>
<p>
    <table>

        <thead>
            <tr>
                <th>Customer name</th>
                <th>Choosen car</th>
                <th>Date and time of the location</th>
                <th>Hours, kms and price</th>
                <th>Comment</th>
                <th>Status</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td>{{customer.name}}</td>
                <td>{{car}}</td>
                <td>{{date_location}}</td>
                <td>{{hours_kms_price}}</td>
                <td>{{note}}</td>
                <td>Pending</td>
            </tr>
        </tbody>
    </table>
</p>

customer/templates/customer/update_reservation_from_customer_1.html
{% extends 'home/header.html' %}
{% load static %}
<!-- this template belong to hanefi -->
{% block content %}

<div class="row container">
    <div class="col s12 m12 l12 xl8 offset-xl2 center ">
      <div class="card white">
        <div class="card-content black-text">
        <!-- Form with no modelForm -->
        <form action="" method="post" onsubmit="myButton.disabled=true;return true;" class="car_update_customer underline_for_modelform_text">
            {% csrf_token %}

            <div class="progress">
                <div class="determinate blue" id="semi_determinate_bar"></div>
            </div>

            <h3>Update</h3>
            <h5>Please select a car</h5>

            {{form.as_p}}

            <br>
            <br>

            <div class="card-action">
            <input type="submit" name="myButton" value="Next" class="btn white black-text waves-effect waves-green">

            <a href="{% url 'cars:all_cars' %}" class="btn white black-text waves-effect waves-green">Choose another car</a>
            </div>

        </form>
        </div>
      </div>
    </div>
</div>

{% endblock content %}

customer/templates/customer/update_reservation_from_customer_2.html
{% extends 'home/header.html' %}
{% load static %}
<!-- this template belong to hanefi -->
{% block content %}

<div class="row container">
    <div class="col s12 m12 l12 xl12">
      <div class="card white">
        <div class="card-image">
            <div class="carousel carousel-slider">
                <a class="carousel-item"><img src="{{car.image1}}" class="responsive-img"></a>
                <a class="carousel-item"><img src="{{car.image2}}" class="responsive-img"></a>

                <a class="carousel-item"><img src="{{car.image3}}" class="responsive-img"></a>
                <a class="carousel-item" ><img src="{{car.image4}}" class="responsive-img"></a>
            </div>
            <span class="card-title">{{car.model}}</span>
        </div>
        <div class="card-content black-text">

        <form action="" method="post" onsubmit="myButton.disabled=true; return true;" class="underline_for_modelform_text">
            {% csrf_token %}

            <div class="progress">
                <div class="determinate blue" id="full_determinate_bar"></div>
            </div>

            <h3 class="center">Update</h3>

            <div class="input-field col s12 m12 l12 xl6">
                <select required name="hours_kms_price">
                    <option value="" disabled selected>Choose your option</option>
                    {% for price in car_price %}
                    <option value="{{price.price_category.hours}} hours | {{price.price_category.kms}} = {{price.car_price}} CHF">{{price}}</option>
                    {% endfor %}
                    <option disabled="disabled" value="For a week contact us please">For a week contact us please</option>

                </select>
                <label>Options selections</label>
            </div>

            <div class="row">
                <div class="col s12 m12 l12 xl6">
                    <span>Date and time of the location</span>
                    <div class="input-field inline">
                        <input required type="datetime-local" id="date_location_start" name="date_location_start" min="{{available_date_check}}">
                    </div>
                </div>
            </div>

            {{form.as_p}}

            <br>

            <input type="submit" name="myButton" value="Confirm Update" class="btn white black-text waves-effect waves-green">

        </form>
        </div>

             <div class="card-action">
                <a href="{% url 'customer:update_reservation_from_customer_1' reservation_pk=reservation_pk %}" class="btn white black-text waves-effect waves-green">Previous page</a>

                <a href="{% url 'customer:customer_dashboard' customer_pk=customer.pk %}" class="btn white black-text waves-effect waves-green">Return to dashboard</a>
             </div>

      </div>
    </div>
</div>


{% endblock content %}

customer/templates/customer/user_settings.html
{% extends 'home/header.html' %}
{% load static %}
<!-- this template belong to perparim -->
{% block content %}

<div class="row container">

    <div class="col s12 m5 l5 xl3">
      <div class="card white">
        <div class="card-image">
          <img src="{{customer.profileURL}}" class="responsive-img">
        </div>
        <div class="card-content black-text center">
            <p>Account settings</p>

            <div class="card-action">
                <a href="{% url 'customer:delete_account_from_customer' customer.id %}" class="btn white black-text waves-effect waves-red">Delete account</a>
            </div>

        </div>
      </div>
    </div>

    <div class="col s12 m7 l7 xl9">
      <div class="card white">
        <div class="card-content">
          <span class="card-title center">Personal infos</span>
          <form method="post" action="" enctype="multipart/form-data" class="white-text" onsubmit="myButton.disabled=true; return true;">
              {% csrf_token %}
              {{form.as_p}}

              <div class="card-action">
                  <input class="btn white black-text waves-effect waves-green" type="submit" name="myButton" value="Confirm">
              </div>

          </form>
        </div>
      </div>
    </div>

</div>

{% endblock %}
           