Projet_44location/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('login_settings.urls')),
    path('', include('cars.urls')),
    path('', include('reservations_management.urls')),
    path('', include('customer.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views

app_name = 'cars'

urlpatterns = [
    path('all_cars/', views.all_cars, name='all_cars'),
    path('car_detail/<str:pk>/', views.car_detail, name='car_detail'),
    path('add_car/', views.add_car, name='add_car'),
    path('update_car/<str:pk>/', views.update_car, name='update_car'),
    path('delete_car/<str:pk>/', views.delete_car, name='delete_car'),
    path('article/', views.article, name='article'),
    path('all_cars/recherche/<str:marque>/', views.recherche, name='recherche')
]

customer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'customer'

urlpatterns = [
    path('settings/<str:pk>/', views.user_settings, name='user_settings'),

    path('delete_account/<str:pk>/', views.delete_account_from_customer, name='delete_account_from_customer'),

    path('customer_dashboard/<str:customer_pk>/', views.customer_dashboard, name='customer_dashboard'),

    path('create_reservation_from_customer/<str:car_pk>/', views.create_reservation_from_customer, name='create_reservation_from_customer'),

    path('update_reservation_from_customer_1/<str:reservation_pk>/', views.update_reservation_from_customer_1, name='update_reservation_from_customer_1'),

    path('update_reservation_from_customer_2/<str:reservation_pk>/', views.update_reservation_from_customer_2, name='update_reservation_from_customer_2'),

    path('delete_reservation_customer/<str:reservation_pk>/', views.delete_reservation_from_customer, name='delete_reservation_from_customer'),

]

reservations_management/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'reservations_management'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),

    path('all_customers_from_admin/', views.all_customers_from_admin, name='all_customers_from_admin'),

    path('create_customer_from_admin/', views.create_customer_from_admin, name='create_customer_from_admin'),

    path('customer_profile_from_admin/<str:pk>/',
         views.customer_profile_from_admin,  name='customer_profile_from_admin'),

    path('delete_customer_admin/<str:pk>/', views.delete_customer_from_admin,  name='delete_customer_from_admin'),

    path('create_reservation_from_admin_1/', views.create_reservation_from_admin_1, name='create_reservation_from_admin_1'),

    path('create_reservation_from_admin_2/<str:customer_pk>/<str:car_pk>/', views.create_reservation_from_admin_2, name='create_reservation_from_admin_2'),

    path('update_reservation_from_admin_1/<str:reservation_pk>/', views.update_reservation_from_admin_1, name='update_reservation_from_admin_1'),

    path('update_reservation_from_admin_2/<str:reservation_pk>/', views.update_reservation_from_admin_2, name='update_reservation_from_admin_2'),

    path('delete_reservation_from_admin/<str:pk>/', views.delete_reservation_from_admin, name='delete_reservation_from_admin'),

]

reservations_management/forms.py
from django.forms import *

from cars.models import Price_category, Price
from .models import *
from django import forms


class ReservationFormFromAdmin1(ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'
        exclude = ['status', 'date_location_start', 'date_location_start', 'note', 'hours_kms_price',
                   'date_location_end']


class ReservationFormFromAdmin2(ModelForm):
    date_location_start = forms.DateTimeField(widget=DateTimeInput({'type': 'datetime-local'}))

    status = forms.ChoiceField(label='Choose a status', choices=STATUS)
    #hours_kms_price = forms.CharField(label='Current options', disabled=True)

    #NumberInput

    def save(self, commit=True):
        reservation = super(ReservationFormFromAdmin2, self).save(commit=False)
        reservation.date_location_start = self.cleaned_data['date_location_start']
        # reservation.note = self.cleaned_data['note']
        reservation.status = self.cleaned_data['status']
        if commit:
            reservation.save()
        return reservation

    class Meta:
        model = Reservation
        fields = '__all__'
        exclude = ['car', 'customer', 'hours_kms_price']

        #widgets = {'note': forms.Select(attrs={'class': 'status_reservation_admin'})}


class CategoryForm(ModelForm):
    class Meta:
        model = Price_category
        fields = '__all__'


class PriceForm(ModelForm):
    class Meta:
        model = Price
        fields = '__all__'
        exclude = ['car', 'price_category', ]


'''
class ReservationFormFromAdmin2(ModelForm):
    date_location_start = forms.DateTimeField(required=True)
    status = forms.CharField(required=True) # how to take back choice in model ?
    note = forms.CharField(required=True)

    def save(self, commit=True):
        reservation = super(ReservationFormFromAdmin2, self).save(commit=False)
        reservation.date_location_start = self.cleaned_data['date_location_start']
        reservation.status = self.cleaned_data['status']
        reservation.note = self.cleaned_data['note']
        if commit:
            reservation.save()
        return reservation

    class Meta:
        model = Reservation
        fields = '__all__'
        exclude = ['car', 'customer']


                widgets = {
                    'name': Textarea(attrs={'cols': 80, 'rows': 20}),
                }

        overriding modelform fields dont work
            def __init__(self, *args, **kwargs):
                super().__init__(*args, **kwargs)
                self.fields['status'].widget.attrs.update(size='10')

'''
#
# date_location_start = forms.DateTimeField(input_formats='2006-10-25 14:30',
#                                           error_messages={'required': 'Choose an option'},
#                                           help_text='You have to choose a date',
#                                           widget=DateTimeInput(attrs={'id': 'testmagique', 'type': 'datetime-local'}))
#
# note = forms.CharField(error_messages={'required': 'put a note'}, initial='test again', help_text='Max 100 character',
#                        required=True)
#
# status = forms.ChoiceField(label='Choose a status', label_suffix=' =', choices=STATUS)

reservations_management/views.py
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, redirect
from django.http import HttpResponse
from cars.models import Price
from login_settings.decorators import admin_only, allowed_user
from customer.forms import NewUserForm
from .forms import *
from .filters import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.utils.html import strip_tags


@login_required(login_url='login')
@admin_only
def dashboard(request):
    reservations = Reservation.objects.all().order_by('-date_created')
    customers = Customer.objects.all()
    total_customers = customers.count()

    # creating a paginator with 1 customer per page
    paginator_customers = Paginator(customers, 5)
    # getting the desired page number from url
    page_number_customers = request.GET.get('customers_page')
    # return the desired page object
    page_obj_customers = paginator_customers.get_page(page_number_customers)

    paginator_reservations = Paginator(reservations, 5)
    page_number_reservations = request.GET.get('reservations_page')
    page_obj_reservations = paginator_reservations.get_page(page_number_reservations)

    total_reservations = reservations.count()
    delivered = reservations.filter(status='Delivered').count()
    pending = reservations.filter(status='Pending').count()
    canceled = reservations.filter(status='Canceled').count()

    context = {'reservations': reservations, 'customers': customers, 'total_reservations': total_reservations, 'delivered': delivered, 'pending': pending, 'canceled': canceled, 'page_obj_customers': page_obj_customers, 'total_customers': total_customers, 'page_obj_reservations': page_obj_reservations}

    return render(request, 'reservations_management/dashboard.html', context)


@login_required(login_url='login')
@admin_only
def all_customers_from_admin(request):
    customers = Customer.objects.all()
    total_customers = customers.count()

    # creating a paginator with 1 customer per page
    paginator_customers = Paginator(customers, 5)
    # getting the desired page number from url
    page_number_customers = request.GET.get('customers_page')
    # return the desired page object
    page_obj_customers = paginator_customers.get_page(page_number_customers)

    context = {'customers': customers, 'page_obj_customers': page_obj_customers, 'total_customers': total_customers}

    return render(request, 'reservations_management/all_customers_from_admin.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def customer_profile_from_admin(request, pk):
    customer = Customer.objects.get(id=pk)

    reservations = customer.reservation_set.all()
    reservation_count = reservations.count()

    myFilter = ReservationFilter(request.GET, queryset=reservations)
    reservations = myFilter.qs

    context = {'customer': customer, 'reservations': reservations, 'reservation_count': reservation_count, 'myFilter': myFilter}
    return render(request, 'reservations_management/customer_profile_from_admin.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def delete_customer_from_admin(request, pk):
    customer = Customer.objects.get(pk=pk)
    if request.method == 'POST':
        customer.delete()
        messages.warning(request, f'{customer} has beed deleted !')
        return redirect('reservations_management:dashboard')
    else:
        context = {'customer': customer}
        return render(request, 'reservations_management/delete_customer_admin.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def create_reservation_from_admin_1(request):
    customers = Customer.objects.all()
    cars = Car.objects.all()
    if request.method == 'POST':
        form = request.POST
        customer_pk = form['customer_id']
        car_pk = form['car_id']
        return redirect("reservations_management:create_reservation_from_admin_2", customer_pk, car_pk)

    context = {'cars': cars, 'customers': customers}
    return render(request, 'reservations_management/reservation_from_admin_car.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def create_reservation_from_admin_2(request, customer_pk, car_pk):
    car_price = Price.objects.all().filter(car=car_pk)
    customer = Customer.objects.get(pk=customer_pk)
    car = Car.objects.get(pk=car_pk)
    form = ReservationFormFromAdmin2()

    # I have to reformat fields in modelform
    # For the datetime i need a calendar

    context = {'car_price': car_price, 'customer': customer, 'car': car, 'form': form}

    if request.method == 'POST':
        form = ReservationFormFromAdmin2(request.POST)
        normalform = request.POST
        if form.is_valid():
            Reservation.objects.create(
                customer=customer,
                car=car,
                hours_kms_price=normalform['hours_kms_price'],
                status=form.cleaned_data.get('status'),
                note=form.cleaned_data.get('note'),
                date_location_start=form.cleaned_data.get('date_location_start'),
            )

            date_location = form.cleaned_data.get('date_location_start')
            status = form.cleaned_data.get('status')
            note = form.cleaned_data.get('note')
            hours_kms_price = normalform['hours_kms_price']

            contextformail = {'date_location': date_location, 'status': status, 'note': note, 'hours_kms_price': hours_kms_price, 'customer': customer, 'car': car}

            subject = f'Your reservation for {car}'
            html_message = render_to_string('reservations_management/reservation_confirm_mail.html', contextformail)
            plain_message = strip_tags(html_message)
            from_email = settings.EMAIL_HOST_USER
            to_email = customer.email

            # date_location_start = form.cleaned_data.get('date_location_start')
            # status = form.cleaned_data.get('status')
            # hours_kms_price = form['hours_kms_price']
            # note = form.cleaned_data.get('note')
            # if note == '':
            #     note = ''
            # else:
            #     note = f"Comment : {note}"
            #
            # subject = f'Your reservation for car {car}'
            # body = {
            #     'note': form.cleaned_data.get('note'),
            # }
            # message = "\n".join(body.values())

            try:
                send_mail(
                    subject,
                    plain_message,
                    from_email,  # from email
                    # [form['email']], another way to pick up the mail from a form
                    [to_email],  # destination email
                    html_message=html_message,
                    fail_silently=False
                )

            except BadHeaderError:
                return HttpResponse('Invalid header found.')

            messages.success(request, f'reservation for {customer} is done !')
            return redirect('reservations_management:dashboard')

        else:
            return HttpResponse('Invalid form.')

    return render(request, 'reservations_management/reservation_from_admin_price.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def update_reservation_from_admin_1(request, reservation_pk):
    reservation = Reservation.objects.get(pk=reservation_pk)
    form = ReservationFormFromAdmin1(instance=reservation)
    if request.method == 'POST':
        form = ReservationFormFromAdmin1(request.POST, instance=reservation)
        if form.is_valid():
            form.save()
            return redirect("reservations_management:update_reservation_from_admin_2", reservation_pk=reservation.pk)

    else:
        context = {'form': form}
        return render(request, 'reservations_management/update_reservation_from_admin_1.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def update_reservation_from_admin_2(request, reservation_pk):
    reservation = Reservation.objects.get(pk=reservation_pk)
    car = reservation.car
    customer = reservation.customer
    form = ReservationFormFromAdmin2(instance=reservation)
    car_price = Price.objects.all().filter(car=car.pk) # car in red must be the name in the Price field
    if request.method == 'POST':
        form = ReservationFormFromAdmin2(request.POST, instance=reservation)
        normalform = request.POST
        if form.is_valid():
            form.save()

        status = form.cleaned_data.get('status')
        date_location = form.cleaned_data.get('date_location_start')
        note = form.cleaned_data.get('note')
        hours_kms_price = normalform['hours_kms_price']


        # if status == 'Confirmed':
        contextformail = {'date_location': date_location, 'status': status, 'note': note, 'hours_kms_price': hours_kms_price, 'customer': customer, 'car': car}

        subject = f'Your reservation update'
        html_message = render_to_string('reservations_management/reservation_confirm_mail.html', contextformail)
        plain_message = strip_tags(html_message)
        from_email = settings.EMAIL_HOST_USER
        to_email = customer.email

        try:
            send_mail(
                subject,
                plain_message,
                from_email,  # from email
                # [form['email']], another way to pick up the mail from a form
                [to_email],  # destination email
                html_message=html_message,
                fail_silently=False
            )
        except BadHeaderError:
            return HttpResponse('Invalid header found.')

        messages.success(request, f'Update done for {customer} !')
        return redirect("reservations_management:dashboard")

    else:

reservations_management/templates/reservations_management/all_customers_from_admin.html
{% extends 'home/header.html' %}
<!-- this template belong to hanefi -->
{% block content %}

<div class="col s12 m12 l12 xl12">
      <div class="card white black-text">
        <div class="card-content">
            <h3 class="center">List of all customers</h3>
            <span class="card-title">Total Customers : {{total_customers}}</span>

            <table class="table responsive-table highlight">
                <thead class="blue">
                    <tr>
                        <th>Customers Infos</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                    </tr>
                </thead>

                <tbody>
                    {% for customer in page_obj_customers %}
                        <tr>
                            <td><a class="btn white black-text waves-effect waves-green" href="{% url 'reservations_management:customer_profile_from_admin' customer.id %}">View</a></td>
                            <td>{{customer.name|upper}}</td>
                            <td>{{customer.email}}</td>
                            <td>{{customer.phone}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="card-action">
          <a href="{% url 'reservations_management:create_customer_from_admin' %}" class="btn white black-text waves-effect waves-green">Create Customer</a>
        </div>

        <div class="center">
        <ul class="pagination">
            <span class="step-links">

            {% if page_obj_customers.has_previous %}
                {# whether the previous page exists #}

                <li><a href="?customers_page=1" class="waves-effect waves-green">first</a></li>

                {# link to the prev page #}
                <li class="waves-effect waves-green"><a href="?customers_page={{page_obj_customers.previous_page_number}}"><i class="material-icons">chevron_left</i></a></li>

            {% endif %}

            <li class="active green"><a href="?customers_page={{page_obj_customers.number}}" class="waves-effect waves-green">{{page_obj_customers.number}}</a></li> {# the current page number #}

            <li> of <a href="?customers_page={{page_obj_customers.paginator.num_pages}}" class="waves-effect waves-green">{{page_obj_customers.paginator.num_pages}}</a></li> {# total page number #}

            {% if page_obj_customers.has_next %}
                {# whether the next page exists #}

                {# link to the next page #}
                <li><a href="?customers_page={{page_obj_customers.next_page_number}}"><i class="material-icons waves-effect waves-green ">chevron_right</i></a></li>

                <li><a href="?customers_page={{page_obj_customers.paginator.num_pages}}" class="waves-effect waves-green">last</a></li>
            {% endif %}

            </span>
            <br><br>
        </ul>
        </div>

      </div>
    </div>

{% endblock %}

reservations_management/templates/reservations_management/create_customer.html
{% extends 'home/header.html' %}
<!-- this template belong to perparim -->
{% block content %}

<div class="row container">
    <div class="col s12 m12 l12 xl12">
      <div class="card white">
        <div class="card-content black-text ">
          <span class="card-title center">Create new customer</span>
        <form method="POST" onsubmit="myButton.disabled=true;return true;" class="underline_for_modelform_text">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="card-action center">
            <button type="submit" name="myButton" class="btn white black-text waves-effect waves-green">Confirm</button>

            <a href="{% url 'reservations_management:dashboard' %}" class="btn white black-text waves-effect waves-green">Back to dashboard</a>
            </div>

        </form>

      </div>
    </div>
</div>

{% endblock %}

reservations_management/templates/reservations_management/customer_profile_from_admin.html
{% extends 'home/header.html' %}
<!-- when no reservation is made from the customer the responsive on phone bug -->
<!-- this template belong to hanefi -->
{% block content %}

<div class="row">
    <div class="col s12 m7 l4 xl4">
      <div class="card white black-text">
        <div class="card-content">
            <span class="card-title">Customer: {{customer.name}}</span>

            <div class="card-action center">

                <a href="{% url 'customer:user_settings' customer.id %}" class="btn white black-text waves-effect waves-green">Update Customer</a>

                <a href="{% url 'reservations_management:delete_customer_from_admin' customer.id %}" class="btn white black-text waves-effect waves-green">Delete Customer</a>

            </div>
        </div>
      </div>
    </div>

    <div class="col s12 m6 l4 xl4">
      <div class="card white black-text">
        <div class="card-content">
            <span class="card-title">Contact Information</span>
            <hr>
            <p>Email: {{customer.email}}</p>
            <p>Phone: {{customer.phone}}</p>
        </div>
      </div>
    </div>

    <div class="col s6 m7 l4 xl4">
      <div class="card cyan black-text">
        <div class="card-content">
          <span class="card-title">Total Reservations</span>
          <p>{{reservation_count}}</p>
        </div>
      </div>
    </div>

</div>

<div class="row">
    <div class="col s12 m12 l12 xl12">
      <div class="card white black-text">
        <div class="card-content">
            <span class="card-title">Reservation details</span>
            <table class="table responsive-table highlight">
                <thead class="blue">
                    <tr>
                        <th>Car</th>
                        <th>Hours | kms | price</th>
                        <th>Date Reserved</th>
                        <th>Status</th>
                        <th>Note</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                </thead>

                <tbody>
                    {% for reservation in reservations %}
                        <tr>
                            <td>{{reservation.car}}</td>
                            <td>{{reservation.hours_kms_price}}</td>
                            <td>{{reservation.date_location_start}}</td>
                            <td>{{reservation.status}}</td>
                            <td>{{reservation.note}}</td>
                            <td><a class="btn white black-text waves-effect waves-green" href="{% url 'reservations_management:update_reservation_from_admin_1' reservation.id %}">Update</a></td>
                            <td><a class="btn white black-text waves-effect waves-red" href="{% url 'reservations_management:delete_reservation_from_admin' reservation.id %}">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
      </div>
    </div>
</div>

<div class="row">
    <div class="col s12 m7 l7 xl4 offset-xl4">
      <div class="card white black-text">
        <div class="card-content">
          <span class="card-title">Search with the filter</span>
          <form method="get" onsubmit="myButton.disabled=true;return true;">

            {% csrf_token %}
            {{myFilter.form.as_p}}

            <div class="card-action">
                <button class="btn white black-text waves-effect waves-green" type="submit" name="myButton">Search</button>
            </div>

          </form>
        </div>
      </div>
    </div>
</div>

{% endblock %}

reservations_management/templates/reservations_management/dashboard.html
{% extends 'home/header.html' %}
<!-- this template belong to hanefi -->
{% block content %}
{% include './includes/status.html' %}

<div class="row">

<div class="col s12 m12 l12 xl12">
  <div class="card white black-text">
    <div class="card-content">
        <span class="card-title center">Recent Reservations</span>
        <table class="table responsive-table highlight">
            <thead class="blue">
                <tr>
                    <th>Customer</th>
                    <th>Car</th>
                    <th>Price</th>
                    <th>Date Reserved</th>
                    <th>Status</th>
<!--                    <th>Note</th>-->
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
            </thead>

            <tbody>
            {% for reservation in page_obj_reservations %}
                <tr>
                    <td>{{reservation.customer.name}}</td>
                    <td>{{reservation.car}}</td>
                    <td>{{reservation.hours_kms_price}}</td>
                    <td>{{reservation.date_location_start}}</td>
                    <td>{{reservation.status}}</td>
<!--                    <td><pre>{{reservation.note|linebreaksbr}}</pre></td>-->
                    <td><a class="btn white black-text waves-effect waves-green" href="{% url 'reservations_management:update_reservation_from_admin_1' reservation.pk %}">Update</a></td>
                    <td><a class="btn white black-text waves-effect waves-red" href="{% url 'reservations_management:delete_reservation_from_admin' reservation.id %}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="card-action">
            <a href="{% url 'reservations_management:create_reservation_from_admin_1' %}" class="btn white black-text waves-effect waves-green">Create Reservation</a>
        </div>

        <div class="center">
            <ul class="pagination">
                <span class="step-links">

                {% if page_obj_reservations.has_previous %}
                    {# whether the previous page exists #}
                <li><a href="?reservations_page=1" class="waves-effect waves-green">first</a></li>

                <li class="waves-effect waves-green"><a href="?reservations_page={{page_obj_reservations.previous_page_number}}"><i class="material-icons">chevron_left</i></a></li>
                    {# link to the prev page #}
                {% endif %}

                <li class="active green"><a href="?reservations_page={{page_obj_reservations.number}}" class="waves-effect waves-green">{{page_obj_reservations.number}}</a></li> {# the current page number #}

                <li> of <a href="?reservations_page={{page_obj_reservations.paginator.num_pages}}" class="waves-effect waves-green">{{page_obj_reservations.paginator.num_pages}}</a></li> {# total page number #}

                {% if page_obj_reservations.has_next %}
                    {# whether the next page exists #}

                    {# link to the next page #}
                <li><a href="?reservations_page={{page_obj_reservations.next_page_number}}"><i class="material-icons waves-effect waves-green ">chevron_right</i></a></li>

                <li><a href="?reservations_page={{page_obj_reservations.paginator.num_pages}}" class="waves-effect waves-green">last</a></li>
                {% endif %}

                </span>
            </ul>
        </div>
    </div>
  </div>
</div>

</div>

{% endblock %}

reservations_management/templates/reservations_management/delete_customer_admin.html
{% extends 'home/header.html' %}
{% load static %}
<!-- this template belong to hanefi -->
{% block content %}

<div class="row container">
    <div class="col s12 m12 l12 xl12 center ">
      <div class="card white black-text">
        <div class="card-content ">
          <span class="card-title">Account deleting</span>
            <p>Are you sure you want to delete customer {{customer}} ?</p>
            <form action="{% url 'reservations_management:delete_customer_from_admin' customer.id %}" method="post" onsubmit="myButton.disabled=true;return true;">
                {% csrf_token %}

                <div class="card-action">
                    <input type="submit" value="Confirm" class="btn white black-text waves-effect waves-green">
                    <a href="{% url 'reservations_management:customer_profile_from_admin' customer.id %}" class="btn white black-text waves-effect waves-red">Cancel</a>
                </div>

            </form>
        </div>
      </div>
    </div>
</div>

{% endblock %}

reservations_management/templates/reservations_management/delete_reservation.html
{% extends 'home/header.html' %}
{% load static %}
<!-- this template belong to hanefi -->
{% block content %}

<div class="row container">
    <div class="col s12 m12 l12 xl12 center">
      <div class="card white black-text">
        <div class="card-content ">
          <span class="card-title">Reservation deleting</span>
            <p>Are you sure you want to delete your reservation for {{reservation}}?</p>
            <form action="{% url 'reservations_management:delete_reservation_from_admin' reservation.id %}" method="post" onsubmit="myButton.disabled=true;return true;">

                {% csrf_token %}

                <div class="card-action">
                    <a href="{% url 'reservations_management:dashboard' %}" class="btn white black-text waves-effect waves-red">Cancel</a>
                    <input type="submit" name="myButton" class="btn white black-text waves-effect waves-green">
                </div>

            </form>
        </div>
      </div>
    </div>
</div>

{% endblock %}

reservations_management/templates/reservations_management/update_reservation_from_admin_1.html
{% extends 'home/header.html' %}
{% load static %}
<!-- this template belong to hanefi -->
{% block content %}

<div class="row container">
    <div class="col s12 m12 x12">
      <div class="card white">
        <div class="card-content black-text">
        <!-- Form with no modelForm -->
        <form action="" method="post" onsubmit="myButton.disabled=true;return true;" class="underline_for_admin_form_text">
            {% csrf_token %}

            <div class="progress">
                <div class="determinate blue" id="semi_determinate_bar" ></div>
            </div>

            <h3 class="center">Customer and Car selection</h3>
            <hr>
            {{form.as_p}}

            <div class="card-action">
            <input type="submit" name="Submit" value="Next" class="btn white black-text waves-effect waves-green">

            <a href="{% url 'cars:all_cars' %}" class="btn white black-text waves-effect waves-green">Choose another car</a>
            </div>

        </form>
        </div>
      </div>
    </div>
</div>

{% endblock content %}