Projet_44location/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('login_settings.urls')),
    path('', include('cars.urls')),
    path('', include('reservations_management.urls')),
    path('', include('customer.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views

app_name = 'cars'

urlpatterns = [
    path('all_cars/', views.all_cars, name='all_cars'),
    path('car_detail/<str:pk>/', views.car_detail, name='car_detail'),
    path('add_car/', views.add_car, name='add_car'),
    path('update_car/<str:pk>/', views.update_car, name='update_car'),
    path('delete_car/<str:pk>/', views.delete_car, name='delete_car'),
    path('article/', views.article, name='article'),
    path('all_cars/recherche/<str:marque>/', views.recherche, name='recherche')
]

customer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'customer'

urlpatterns = [
    path('settings/<str:pk>/', views.user_settings, name='user_settings'),

    path('delete_account/<str:pk>/', views.delete_account_from_customer, name='delete_account_from_customer'),

    path('customer_dashboard/<str:customer_pk>/', views.customer_dashboard, name='customer_dashboard'),

    path('create_reservation_from_customer/<str:car_pk>/', views.create_reservation_from_customer, name='create_reservation_from_customer'),

    path('update_reservation_from_customer_1/<str:reservation_pk>/', views.update_reservation_from_customer_1, name='update_reservation_from_customer_1'),

    path('update_reservation_from_customer_2/<str:reservation_pk>/', views.update_reservation_from_customer_2, name='update_reservation_from_customer_2'),

    path('delete_reservation_customer/<str:reservation_pk>/', views.delete_reservation_from_customer, name='delete_reservation_from_customer'),

]

cars/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User


class Article(models.Model):
    Titre = models.CharField(max_length=100, null=True, blank=True)
    Texte = models.TextField(null=True, blank=True)


class Brand(models.Model):
    name = models.CharField(max_length=200)
    brand_image = models.ImageField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Brands"

    def __str__(self):
        return self.name


class Car(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True, blank=True)
    model = models.CharField(max_length=200)
    max_speed = models.CharField(max_length=200)
    description = models.TextField()
    car_image1 = models.ImageField(null=True, blank=True)
    car_image2 = models.ImageField(null=True, blank=True)
    car_image3 = models.ImageField(null=True, blank=True)
    car_image4 = models.ImageField(null=True, blank=True)
    buy_date = models.DateField(null=True, blank=True)
    transmission = models.CharField(max_length=200, null=True, blank=True)
    carburant = models.CharField(max_length=200, null=True, blank=True)
    consumption = models.CharField(max_length=200, null=True, blank=True)
    price_categories = models.ManyToManyField('Price_category', through='Price', blank=True)

    @property
    def image1(self):
        try:
            url = self.car_image1.url
        except:
            url = ''
        return url

    @property
    def image2(self):
        try:
            url = self.car_image2.url
        except:
            url = ''
        return url

    @property
    def image3(self):
        try:
            url = self.car_image3.url
        except:
            url = ''
        return url

    @property
    def image4(self):
        try:
            url = self.car_image4.url
        except:
            url = ''
        return url

    @property
    def get_reservation_car_detail(self):
        prices = self.price_set.all()

        return ''

    def __str__(self):
        return self.model


class Price_category(models.Model):
    nb_hours = (
        ('4h', '4h'),
        ('6h', '6h'),
        ('12h', '12h'),
        ('24h', '24h'),
        ('Week-end', 'Week-end'),
    )
    nb_kms = (
        ('150 kms', '150 kms'),
        ('200 kms', '200 kms'),
        ('350 kms', '350 kms'),
        ('500 kms', '500 kms'),
        ('900 kms', '900 kms'),
        ('illimited kms', 'illimited kms'),
    )
    hours = models.CharField(max_length=40, null=True, blank=True, choices=nb_hours)
    kms = models.CharField(null=True, blank=True, max_length=40, choices=nb_kms)

    def __str__(self):
        return f' {self.kms} for {self.hours}'


class Price(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True, blank=True)
    price_category = models.ForeignKey(Price_category, on_delete=models.SET_NULL, null=True, blank=True)
    car_price = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.price_category.hours} {self.price_category.kms} = {self.car_price} Chf'

'''
    def __str__(self):
        return self.car_price
        '''

cars/forms.py
from django.forms import ModelForm
from .models import *


class CarForm(ModelForm):

    class Meta:
        model = Car
        fields = '__all__'

cars/views.py
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import *
from login_settings.decorators import allowed_user
from .models import *
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.forms import inlineformset_factory
from django.urls import reverse


def recherche(request, marque):
    resultats = Brand.objects.filter(name__icontains=marque).values()
    return JsonResponse(list(resultats), safe=False)


def all_cars(request):
    brand = request.GET.get('brand')
    if brand == None:
        cars = Car.objects.all()
    else:
        cars = Car.objects.filter(brand__name=brand)

    brands = Brand.objects.all()
    context = {'brands': brands, 'cars': cars}

    return render(request, "cars/all_cars.html", context)


def car_detail(request, pk):
    car = Car.objects.get(id=pk)
    car_price = Price.objects.all().filter(car=pk)
    context = {'car': car, 'car_price': car_price}

    return render(request, "cars/car_detail.html", context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def add_car(request):
    brands = Brand.objects.all()

    if request.method == 'POST':
        data = request.POST
        car_image = request.FILES.get('car_image1')

        if data['brand'] != 'none':
            brand = Brand.objects.get(id=data['brand'])
        elif data['brand_new'] != '':
            brand, created = Brand.objects.get_or_create(name=data['brand_new'], brand_image=car_image)
        else:
            brand = None

        car = Car.objects.create(brand=brand,
                                description=data['description'],
                                car_image1=car_image,
                                buy_date=data['buy_date'],
                                carburant=data['carburant'],
                                transmission=data['transmission'],
                                consumption=data['consumption'],
                                max_speed=data['max_speed'],
                                model=data['model'],
                                )
        messages.success(request, f'A car has been added !')
        return redirect('cars:all_cars')

    context = {'brands': brands}

    return render(request, "cars/add_car.html", context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def update_car(request, pk):
    car = Car.objects.get(pk=pk)
    form = CarForm(instance=car)
    if request.method == 'POST':
        form = CarForm(request.POST, request.FILES, instance=car)
        if form.is_valid():
            car = form.save(commit=False)
            car.car_image2 = form.cleaned_data.get('car_image2')
            car.save()
            messages.success(request, f'{car} has been updated !')
            return redirect('cars:all_cars')

    context = {'form': form}
    return render(request, 'cars/update_car.html', context)


@login_required(login_url='login')
@allowed_user(allowed_roles=['admin'])
def delete_car(request, pk):
    car = Car.objects.get(pk=pk)
    if request.method == 'POST':
        car.delete()
        messages.warning(request, f'{car} has been deleted')
        return redirect('cars:all_cars')

    context = {'car': car}
    return render(request, 'cars/delete_car.html', context)


def article(request):
    art = Article.objects.all()
    context = {'article': art}

    return render(request, 'cars/article.html', context)

cars/templates/cars/add_car.html
{% extends 'home/header.html' %}
<!-- this template belong to adam -->
{% block content %}

<div class="row">
  <div class="col s12 m12 l12 xl12">
    <div class="card white darken-1">
      <div class="card-content black-text">
        <span class="card-title">Add Car</span>
        <form method="post" enctype="multipart/form-data" onsubmit="myButton.disabled=true;return true;">
        {% csrf_token %}
        <div class="input-field col s12">
          <select name="brand">
            <option value="none">Choose your option</option>
              {% for brand in brands %}
            <option value="{{brand.id}}">{{brand.name}}</option>
          {% endfor %}
          </select>
          <label>Brand</label>
        </div>

        <div class="input-field col s7">
        <label for="brand_new">Create a new brand</label>
        <input name="brand_new" id="brand_new" type="text" class="validate">
        </div>

        <div class="input-field col s5">
        <label for="model">model</label>
        <input name="model" id="model" type="text" class="validate">
        </div>

        <div class="input-field col s4">
        <label for="max_speed">max_speed</label>
        <input name="max_speed" id="max_speed" type="text" class="validate">
        </div>

        <div class="input-field col s8">
        <label for="buy_date">buy_date</label>
        <input name="buy_date" placeholder="buy_date" id="buy_date" type="date" class="validate">
        </div>

        <div class="input-field col s6">
        <label for="transmission">transmission</label>
        <input name="transmission" id="transmission" type="text" class="validate">
        </div>

        <div class="input-field col s6">
        <label for="carburant">carburant</label>
        <input name="carburant" id="carburant" type="text" class="validate">
        </div>

        <div class="input-field col s4">
        <label for="consumption">consumption</label>
        <input name="consumption" id="consumption" type="text" class="validate">
        </div>


        <div class="input-field col s8">
        <label for="description">Description</label>
        <input name="description" id="description" type="text" class="validate">
        </div>

        <div class="input-field col s12">
        <input name="car_image1" id="car_image1" type="file" class="validate">
        </div>

        <br><br>
        <button type="submit" class="btn white black-text waves-effect waves-green" name="myButton">Submit</button>

        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

cars/templates/cars/all_cars.html
{% extends 'home/header.html' %}

{% block content %}

<div class="row">

    <div class="col s8 m6 l3 xl3">
      <div class="card hoverable white darken-1">
        <div class="card-content black-text">
            <span class="card-title center">Brands</span>
            <div class="collection hoverable " >

                <a href="{% url 'cars:all_cars' %}" class="collection-item white darken-1 black-text waves-effect waves-green">All</a>
                {% for brand in brands %}
                <table class="highlight">
                    <tbody>
                    <tr>
                        <td><a href="{% url 'cars:all_cars' %}?brand={{brand.name}}" class="collection-item active white darken-1 black-text waves-effect waves-green" >{{brand.name}}</a></td>
                    </tr>
                    </tbody>
                </table>
                {% endfor %}
            <form>
                    <input type="text" id="recherche" placeholder="Cherchez votre voiture..." onkeyup="requeteXML()">
                    <button type="submit" id="bouton-recherche">Rechercher</button>
                </form>
                <div id="affichage">
                </div>
                {% if user.is_authenticated and request.user.is_staff %}
                        <a href="{% url 'cars:add_car' %}" class="btn collection-item active white darken-1 black-text waves-effect waves-green">Add a car</a>

                {% endif %}

            </div>
        </div>
      </div>
    </div>

    <div class="col s12 m9 l9 xl9">
    {% for car in cars %}
      <div class="col s12 m12 l6 xl4">
      <div class="card medium hoverable">
        <div class="card-image">
<!--          <img class="responsive-img" src="{{car.image1}}" id="image_ajustement">-->
            <div class="carousel carousel-slider">
                <a class="carousel-item"><img id="imageVoiture{{forloop.counter}}" src="{{car.image1}}" class="responsive-img"></a>
                <a class="carousel-item"><img src="{{car.image2}}" class="responsive-img"></a>

                <a class="carousel-item"><img src="{{car.image3}}" class="responsive-img"></a>
                <a class="carousel-item" ><img src="{{car.image4}}" class="responsive-img"></a>
            </div>
            <span class="card-title">{{car.model}}</span>
        </div>
<!--        <div class="card-content white darken-1 black-text center">-->
<!--          <p>{{car}}</p>-->
<!--          <p>{{car.description|safe}}</p>-->
<!--        </div>-->
      <p id="textZoom{{forloop.counter}}"></p>
        <div class="card-action white darken-1 ">
            <a href="{% url 'cars:car_detail' car.pk %}" class="btn white black-text waves-effect waves-green">Details</a>


            <!-- Modal Trigger -->
<!--            <a class="btn white black-text waves-effect waves-green modal-trigger" href="#modal1">Details</a>-->

            <!-- Modal Structure -->
<!--            <div id="modal1" class="modal modal-fixed-footer">-->
<!--                <div class="modal-content">-->
<!--                    <h4>{{car}}</h4>-->
<!--                    <p>Description : {{car.description|safe}}</p>-->
<!--                    <p>Max speed : {{car.max_speed}}</p>-->
<!--                    <p>Transmission : {{car.transmission}}</p>-->
<!--                    <p>Consumption : {{car.consumption}}</p>-->
<!--                    <p>Carburant : {{car.carburant}}</p>-->
<!--                    <p>Carburant : {{car.carburant}}</p>-->
<!--                </div>-->
<!--                <div class="modal-footer">-->
<!--                <a href="#!" class="modal-close waves-effect black-text waves-green btn-flat">Return</a>-->
<!--                </div>-->
<!--            </div>-->


            {% if not user.is_staff %}
                <a href="{% url 'customer:create_reservation_from_customer' car_pk=car.pk %}" class="btn white black-text waves-effect waves-green">Reserve</a>
            {% endif %}
            <button id="zoom{{forloop.counter}}" class="btn white black-text waves-effect waves-green">zoom</button>
          {% if user.is_authenticated and request.user.is_staff %}
              <a href="{% url 'cars:update_car' car.id %}" class="btn collection-item active white darken-1 black-text waves-effect waves-green">Update</a>

              <a href="{% url 'cars:delete_car' car.id %}" class="btn collection-item active white darken-1 black-text waves-effect waves-red">Delete</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% empty %}
    <h3>No Cars</h3>
    {% endfor %}

    </div>

</div>
<script type="text/javascript">
      var nb_voit = {{cars|length}};
      //console.log(nb_voit);

      // Récuperation de l'image
      var img = document.getElementById('imageVoiture');
      // Function qui aggrandit l'image
      function enlargeImg(i) {
        var img = document.getElementById('imageVoiture' + i);
        var btn = document.getElementById('zoom'+i);
        var divAInserer = document.getElementById('textZoom'+i);
        var textAInserer = document.createTextNode('Image maintenant zoomée');



        if (img.style.transform == "scale(1.5)")
        {
        img.style.transform = "scale(1)";
        btn.textContent = "zoom";
       // suppressionDiv();
        divAInserer.remove();
        //console.log(i);
        }
        else
        {
        img.style.transform = "scale(1.5)";
        btn.textContent = "dézoomer";
        //ajoutTextDiv();
        divAInserer.appendChild(textAInserer);
        }
        // Effet d'animation
        img.style.transition = "transform 0.25s ease";
      }

     /* function ajoutTextDiv(){
         // console.log('helloppp')
          let divAjoutee = document.getElementById('textZoom');
          let textAjoute = document.createTextNode('Image maintenant zoomée');

          divAjoutee.appendChild(textAjoute);
      }

      function suppressionDiv(){
          let suppDiv = document.getElementById('textZoom');
          suppDiv.remove()
      }*/

      //var ajout = ajoutTextDiv;
      //var suppression = suppressionDiv;

      for (let i = 1; i < nb_voit; i++) {
        document.getElementById('zoom'+i).addEventListener('click', function(){
        enlargeImg(i);
        })
       }

      document.addEventListener("DOMContentLoaded", function () {
      document.getElementById("bouton-recherche").addEventListener("click", function (e) {
        e.preventDefault();
        requeteXML();
      });

      document.getElementById("barre-recherche").addEventListener("keypress", function (e) {
        if (e.key === "Enter") {
          e.preventDefault();
          requeteXML();
        }
      });
});
      function requeteXML() {
        var query = document.getElementById("recherche").value;
        var xhr = new XMLHttpRequest();

        xhr.open("GET", "recherche/" + query);
        xhr.onreadystatechange = function () {
        var voitures = JSON.parse(xhr.responseText);
        var list = "<ul>";
          if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
            for (var i = 0; i < voitures.length; i++){
                list += "<li>" + voitures[i].name + "</li>";
            }
            list += "</ul>";
            document.getElementById("affichage").innerHTML = list;

          }
        }
;
        xhr.send();
      }



</script>
{% endblock %}

cars/templates/cars/article.html
{% extends 'home/header.html' %}

{% block content %}

<div class="row">
    <div class="col s8 m6 l3 xl3">
        <div class="card hoverable white darken-1">
            <div class=card-content black-text">
            {% for a in article %}
                <div class="col s24 m24 l12 x8">
                    <div class="card medium hoverable">
                        <div class="card-image">
                            <div class="carousel carousel-slider">
                                <h2>{{ a.Titre }}</h2>
                                <br>
                                <br>
                                {{ a.Texte }}

                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
            <button>Retour</button>

            </div>

        </div>

    </div>

</div>

{% endblock %}

cars/templates/cars/car_detail.html
{% extends 'home/header.html' %}
<!-- this template belong to adam -->
{% block content %}

<div class="row container">

    <div class="col s12 m12 l12 xl10 offset-xl1">
        <div class="card white ">

            <div class="card-image">
                <div class="carousel carousel-slider">
                    <a class="carousel-item"><img src="{{car.image1}}" class="responsive-img"></a>
                    <a class="carousel-item"><img src="{{car.image2}}" class="responsive-img"></a>

                    <a class="carousel-item"><img src="{{car.image3}}" class="responsive-img"></a>
                    <a class="carousel-item" ><img src="{{car.image4}}" class="responsive-img"></a>
                </div>
                <span class="card-title">{{car.model}}</span>
            </div>

            <div class="card-content black-text">
                <table class="table responsive-table highlight">
                    <thead>
                    <tr class="blue">
                        <th>Max speed</th>
                        <th>Consumption</th>
                        <th>Carburant</th>
                        <th>Transmission</th>
                        <th>Description</th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        <td>{{car.max_speed}}</td>
                        <td>{{car.consumption}}</td>
                        <td>{{car.carburant}}</td>
                        <td>{{car.transmission}}</td>
                        <td>{{car.description|safe}}</td>
                    </tr>
                    </tbody>

                </table>

                <div class="input-field col s12 m12 l12 xl6">
                    <select required name="hours_kms_price">
                        <option value="" disabled selected>Click to see</option>
                        {% for price in car_price %}
                        <option value="{{price.price_category.hours}} hours | {{price.price_category.kms}} = {{price.car_price}} CHF">{{price}}</option>
                        {% endfor %}
                        <option value="For a week">For a week contact us</option>
                    </select>
                    <label>Prices</label>
                </div>

                <div class="card-action">
                    <a href="{% url 'customer:create_reservation_from_customer' car_pk=car.id %}" class="btn white black-text waves-effect waves-green">Reserve</a>

                    <a href="{% url 'cars:all_cars' %}" class="btn white black-text waves-effect waves-green">Back to Cars</a>
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}

cars/templates/cars/delete_car.html
{% extends 'home/header.html' %}
<!-- this template belong to adam -->
{% block content %}

<div class="row container">
    <div class="col s12 m12 l12 xl12">
      <div class="card white darken-1">
        <div class="card-content black-text center">
            <span class="card-title">Delete Car</span>
            <form method="post" onsubmit="myButton.disabled=true;return true;">
            {% csrf_token %}
            <p>Are you sure you want to delete car {{car}} ?</p>
            <br>

            <div class="card-action">
            <button type="submit" class="btn white black-text waves-effect waves-green" name="myButton">Delete</button>

            <a href="{% url 'cars:all_cars' %}" class="btn white black-text waves-effect waves-green">Cancel</a>
            </div>

            </form>
        </div>
      </div>
    </div>
</div>

{% endblock content %}

cars/templates/cars/update_car.html
{% extends 'home/header.html' %}
<!-- this template belong to adam -->
{% block content %}

<div class="row container">
    <div class="col s10 m8 l8 xl12">
      <div class="card white darken-1">
        <div class="card-content black-text">
            <span class="card-title center">Update Car</span>
            <form method="post" onsubmit="myButton.disabled=true;return true;" class="underline_for_modelform_text">
            {% csrf_token %}
            {{form.as_p}}

            <div class="card-action">
            <button type="submit" class="btn white black-text waves-effect waves-green" name="myButton">Update</button>

            <a href="{% url 'cars:all_cars' %}" class="btn white black-text waves-effect waves-green">Cancel</a>
            </div>

            </form>
        </div>
      </div>
    </div>
</div>

{% endblock content %}