Projet_44location/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('login_settings.urls')),
    path('', include('cars.urls')),
    path('', include('reservations_management.urls')),
    path('', include('customer.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views

app_name = 'cars'

urlpatterns = [
    path('all_cars/', views.all_cars, name='all_cars'),
    path('car_detail/<str:pk>/', views.car_detail, name='car_detail'),
    path('add_car/', views.add_car, name='add_car'),
    path('update_car/<str:pk>/', views.update_car, name='update_car'),
    path('delete_car/<str:pk>/', views.delete_car, name='delete_car'),
    path('article/', views.article, name='article'),
    path('all_cars/recherche/<str:marque>/', views.recherche, name='recherche')
]

customer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'customer'

urlpatterns = [
    path('settings/<str:pk>/', views.user_settings, name='user_settings'),

    path('delete_account/<str:pk>/', views.delete_account_from_customer, name='delete_account_from_customer'),

    path('customer_dashboard/<str:customer_pk>/', views.customer_dashboard, name='customer_dashboard'),

    path('create_reservation_from_customer/<str:car_pk>/', views.create_reservation_from_customer, name='create_reservation_from_customer'),

    path('update_reservation_from_customer_1/<str:reservation_pk>/', views.update_reservation_from_customer_1, name='update_reservation_from_customer_1'),

    path('update_reservation_from_customer_2/<str:reservation_pk>/', views.update_reservation_from_customer_2, name='update_reservation_from_customer_2'),

    path('delete_reservation_customer/<str:reservation_pk>/', views.delete_reservation_from_customer, name='delete_reservation_from_customer'),

]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('search_car-<car>/', views.recherche, name='search_car'),
]

reservations_management/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'reservations_management'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),

    path('all_customers_from_admin/', views.all_customers_from_admin, name='all_customers_from_admin'),

    path('create_customer_from_admin/', views.create_customer_from_admin, name='create_customer_from_admin'),

    path('customer_profile_from_admin/<str:pk>/',
         views.customer_profile_from_admin,  name='customer_profile_from_admin'),

    path('delete_customer_admin/<str:pk>/', views.delete_customer_from_admin,  name='delete_customer_from_admin'),

    path('create_reservation_from_admin_1/', views.create_reservation_from_admin_1, name='create_reservation_from_admin_1'),

    path('create_reservation_from_admin_2/<str:customer_pk>/<str:car_pk>/', views.create_reservation_from_admin_2, name='create_reservation_from_admin_2'),

    path('update_reservation_from_admin_1/<str:reservation_pk>/', views.update_reservation_from_admin_1, name='update_reservation_from_admin_1'),

    path('update_reservation_from_admin_2/<str:reservation_pk>/', views.update_reservation_from_admin_2, name='update_reservation_from_admin_2'),

    path('delete_reservation_from_admin/<str:pk>/', views.delete_reservation_from_admin, name='delete_reservation_from_admin'),

]

home/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)
    message = models.TextField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from .models import *
from cars.models import Car
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags


def homepage(request):
    cars = Car.objects.all()
    context = {'cars': cars}
    return render(request, 'home/homepage.html', context)


def about_us(request):
    context = {}
    return render(request, 'home/about_us.html', context)


def contact_us(request):
    if request.method == "POST":
        form = request.POST
        Contact.objects.create(
            name=form['name'],
            email=form['email'],
            phone=form['phone'],
            message=form['message'],
        )

        name = form['name']
        email = form['email']
        phone = form['phone']
        message = form['message']

        contextformail = {'name': name, 'email': email, 'phone': phone, 'message': message}

        subject = f'Message from {name} from the contact form'
        html_message = render_to_string('home/contact_mail_sent.html', contextformail)
        plain_message = strip_tags(html_message)
        from_email = email
        to_email = settings.EMAIL_HOST_USER

        try:
            send_mail(
                subject,
                plain_message,
                from_email,
                [to_email],
                html_message=html_message,
                fail_silently=False
            )
        except BadHeaderError:
            return HttpResponse('Invalid header found')

        messages.success(request, 'Your message has been sent to an admin !')
        return redirect('home:homepage')

    return render(request, 'home/contact_us.html')

def recherche(request, insert):
    cars = Brand.objects.filter(name__icontains=insert)
    items = {"item": []}
    for car in cars:
        items["item"].append(car.name)
    time.sleep(5)
    return JsonResponse({'items': items})


# Another way to send mail
# send_mail(
#         subject,
#         form['message'] + '\n from \n' + form['email'],
#         settings.EMAIL_HOST_USER,
#         #[form['email']],
#         ['GentilleOurson@gmail.com'],
#         fail_silently=False
#     )

home/templates/home/includes/footer.html
<!-- FOOTER -->
<div class="footer-copyright">
  <div class="container">
    <table>
      <tr>
        <td>© 44location 2021</td>
        <td><a  href="https://www.facebook.com/" class="fa fa-facebook" target="_blank" > Facebook </a></td>
        <td><a  href="https://www.instagram.com/44location/" class="fa fa-instagram"> Instagram </a></td>
        <td><a  href="https://twitter.com/" class="fa fa-twitter" target="_blank"> Twitter </a></td>
      </tr>
    </table>
  </div>
</div>

home/templates/home/includes/navbar.html
{% load active_link_tags %}
{% load static %}


<title>44location</title>

<div class="navbar-fixed">
  <nav>
  <div class="nav-wrapper ">

    <a href="/" class="brand-logo"><img src="{% static '/images/logo-44location.png' %}" id="logo"></a>

    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <!-- normal navbar -->
      <ul class="right hide-on-med-and-down">
        {% if user.is_authenticated and not request.user.is_staff  %}

          {% url 'customer:user_settings' request.user.customer.id as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}" >Connected as :  {{user.username}}</a></li>

          {% url 'customer:customer_dashboard' request.user.customer.pk as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}" class="{% active_link 'customer:customer_dashboard'  'my_custom_active_link' strict=True %}">My reservation</a></li>

          {% url 'cars:all_cars' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}">Cars</a></li>

          {% url 'home:about_us' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}">About us</a></li>

          {% url 'home:contact_us' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}">Contact</a></li>

          <li class="{% active_link 'logout' 'my_custom_active_link' %}"><a href="{% url 'logout' %}">Logout</a></li>

        {% elif user.is_authenticated and request.user.is_staff %}

          {% url 'home:homepage' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}">Admin : {{user.username}}</a></li>

          {% url 'reservations_management:dashboard' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}">Dashboard</a></li>

          {% url 'cars:all_cars' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}">Cars</a></li>

          {% url 'reservations_management:all_customers_from_admin' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{% url 'reservations_management:all_customers_from_admin' %}">Customers</a></li>

          <li><a href="{% url 'logout' %}">Logout</a></li>

        {% else %}

          {% url 'cars:all_cars' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}">Cars</a></li>

          {% url 'home:about_us' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}">About us</a></li>

          {% url 'home:contact_us' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}">Contact</a></li>

          {% url 'login' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{% url 'login' %}">Login</a></li>

          {% url 'register' as url %}
          <li class="{% if request.path == url %}my_custom_active_link{% endif %}"><a href="{{url}}">Register</a></li>
        {% endif %}
    </ul>

  </div>
  </nav>
</div>

  <!-- sidenav -->
  <ul class="sidenav" id="mobile-demo">
      {% if user.is_authenticated and not request.user.is_staff  %}
        <li><a href="{% url 'customer:user_settings' request.user.customer.id %}" class="btn white black-text waves-effect waves-green">Connected as :  {{user.username}}</a></li>
        <li><a href="{% url 'customer:customer_dashboard' customer_pk=request.user.customer.pk %}" class="btn white black-text waves-effect waves-green">My reservation</a></li>
        <li><a href="{% url 'cars:all_cars' %}" class="btn white black-text waves-effect waves-green">Cars</a></li>
        <li><a href="{% url 'home:about_us' %}" class="btn white black-text waves-effect waves-green">About us</a></li>
        <li><a href="{% url 'home:contact_us' %}" class="btn white black-text waves-effect waves-green">Contact</a></li>
        <li><a href="{% url 'logout' %}" class="btn white black-text waves-effect waves-green">Logout</a></li>

      {% elif user.is_authenticated and request.user.is_staff %}

        <li>Admin : {{user.username}}</li>

        <li><a href="{% url 'reservations_management:dashboard' %}" class="btn white black-text waves-effect waves-green" class="btn white black-text waves-effect waves-green">Dashboard</a></li>

        <li><a href="{% url 'cars:all_cars' %}" class="btn white black-text waves-effect waves-green" class="btn white black-text waves-effect waves-green">Cars</a></li>

        <li><a href="{% url 'reservations_management:all_customers_from_admin' %}" class="btn white black-text waves-effect waves-green">Customers</a></li>

        <li><a href="{% url 'logout' %}" class="btn white black-text waves-effect waves-green">Logout</a></li>

      {% else %}

        <li><a href="{% url 'cars:all_cars' %}" class="btn white black-text waves-effect waves-green">Cars</a></li>

        <li><a href="{% url 'home:about_us' %}" class="btn white black-text waves-effect waves-green">About us</a></li>

        <li><a href="{% url 'home:contact_us' %}" class="btn white black-text waves-effect waves-green">Contact</a></li>

        <li><a href="{% url 'login' %}" class="btn white black-text waves-effect waves-green">Login</a></li>

        <li><a href="{% url 'register' %}" class="btn white black-text waves-effect waves-green">Register</a></li>
      {% endif %}
  </ul>


<!--This was for the active link nav with javascript didn't work-->
<!--  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>-->

<!--  <script type="text/javascript">-->
<!--      $(document).on('click', 'ul li', function(e){-->
<!--          e.preventDefault();-->
<!--          $(this).addClass('bobop').siblings.removeClass('bobop');-->
<!--      })-->
<!--  </script>-->